source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target "FlashWord" do
  pod 'MagicalRecord/Shorthand'
  pod 'SnapKit', '~> 0.15.0'
  pod 'ReactiveCocoa', '~> 4.2.2'
  # pod 'RxSwift', '~> 3.0.0-beta.1'
  # pod 'RxCocoa', '~> 3.0.0-beta.1'
  # pod 'MagicalRecord/Shorthand'
  # pod 'SnapKit', '~> 3.0'

  # pod 'Alamofire', '~> 3.4'
  # pod 'IBAnimatable'
  # pod 'paper-onboarding'
  # pod "AsyncSwift"

  # pod 'Siren'
end
