source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target "FlashWord" do
  pod 'RxSwift', '~> 2.0'
  pod 'RxCocoa', '~> 2.0'
  pod 'MagicalRecord/Shorthand'
  pod 'SnapKit', '~> 0.15.0'
  
  # pod 'Alamofire', '~> 3.4'
  # pod 'IBAnimatable'
  # pod 'paper-onboarding'
  # pod "AsyncSwift"

  # pod 'Siren'
end
